image:
listenPort:
resource:
  maxMem:
  maxCPU:
env:
  - MONGO_URI:
  - BROKER_URL:
  - SENTRY_DSN:
  - AUTH_ADDRESS: 0xF25AbDb08ff0e0e5561198A53F1325dcfBE92428
  - AUTH_PRIVATE_KEY: 98102796d0dfe116f5af6e9a3c10dc38d316f6c98b3ded8d008b962c7d126460
  - PUBLIC_PATH: 
  - REDIS_CLUSTER: 
  - REDLOCK_REDIS: 
  - BSC_RPC_URI: 
  - CHAIN_ID: 
  - IPFS_TOKEN: 
  - WALLET_IAPI: 
  - ASSETS: 
  - RECAPTCHA3_PRIVATE_KEY: 
  - SIMPLEX_URI: